###
POST http://localhost:900/almacen HTTP/1.1
Content-type: application/json

{
    "nombre" : "Almacen 1",
    "ubicacion" : "Mario-Bravo 546",
    "email": "almacen1@gmail.com",
    "telefono": 11234567

}

###
GET http://localhost:900/almacen HTTP/1.1

###
GET http://localhost:900/almacen/62aa375f550ac92cb0ab0c97 HTTP/1.1
 


###
PUT http://localhost:900/almacen/62aa375f550ac92cb0ab0c97 HTTP/1.1
Content-type: application/json

{
    "nombre" : "Almacen 1",
    "ubicacion" : "Honduras 546",
    "email": "almacen1@gmail.com",
    "telefono": 11674567

}

###
DELETE http://localhost:900/almacen/62aa375f550ac92cb0ab0c97 HTTP/1.1