###
POST http://localhost:900/users HTTP/1.1
Content-type: application/json

{
    "email": "daminpsca@gmail.com",
    "name" : "dmin",
    "surname": "psa",
    "edad": 29

}

###
GET http://localhost:900/users HTTP/1.1

###
GET http://localhost:900/users/62a8cd5c06d2a8b1abc00084 HTTP/1.1
 


###
PUT http://localhost:900/users/62a8cd5c06d2a8b1abc00084 HTTP/1.1
Content-type: application/json

{
    "email": "usuarioactualizado@gmail.com",
    "name" : "dusuario",
    "surname": "actualizad",
    "edad": 37

}

###
DELETE http://localhost:900/users/62a8cd5c06d2a8b1abc00084 HTTP/1.1