###
POST http://localhost:900/laboratorio HTTP/1.1
Content-type: application/json

{
    "nombre" : "laboratorio 1",
    "ubicacion" : "Mario-Bravo 546",
    "email": "laboratorio1@gmail.com",
    "telefono": 11234567

}

###
GET http://localhost:900/laboratorio HTTP/1.1

###
GET http://localhost:900/laboratorio/62a8cd5c06d2a8b1abc00084 HTTP/1.1
 


###
PUT http://localhost:900/laboratorio/62a8cd5c06d2a8b1abc00084 HTTP/1.1
Content-type: application/json

{
    "nombre" : "laboratorio 1",
    "ubicacion" : "Honduras 546",
    "email": "laboratorio1@gmail.com",
    "telefono": 11674567

}

###
DELETE http://localhost:900/laboratorio/62a8cd5c06d2a8b1abc00084 HTTP/1.1