###
POST http://localhost:900/parte HTTP/1.1
Content-type: application/json

{
    "descripcion" : "parte 1",
    "cantpartesConsum" : 5,
    "cantpartesDesper": 9

}

###
GET http://localhost:900/parte HTTP/1.1

###
GET http://localhost:900/parte/62aa35eff533d042de86463e HTTP/1.1
 


###
PUT http://localhost:900/parte/62aa35eff533d042de86463e HTTP/1.1
Content-type: application/json

{
    "descripcion" : "parte 1",
    "cantpartesConsum" : 5,
    "cantpartesDesper": 9

}

###
DELETE http://localhost:900/parte/62aa35eff533d042de86463e HTTP/1.1